
import "./globals.css";

import HeaderController from "@/components/HeaderController";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-white h-full max-w-[1500px] mx-auto px-2 sm:px-6">
      <body className="antialiased">
        <HeaderController/>
        {children}
      </body>
    </html>
  );
}
